import 'package:hive_flutter/hive_flutter.dart';
import '../models/challenge.dart';

class HiveService {
  static const String challengesBoxName = 'challenges';

  bool _isInitialized = false;

  Future<void> init() async {
    if (_isInitialized) return;

    // Register adapter (generated by build_runner)
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(ChallengeAdapter());
    }

    _isInitialized = true;
  }

  Future<Box<Challenge>> _openBox() async {
    await init();
    if (Hive.isBoxOpen(challengesBoxName)) {
      return Hive.box<Challenge>(challengesBoxName);
    }
    return await Hive.openBox<Challenge>(challengesBoxName);
  }

  Future<List<Challenge>> getAllChallenges() async {
    final box = await _openBox();
    return box.values.toList();
  }

  Future<Challenge?> getChallenge(String id) async {
    final box = await _openBox();
    return box.get(id);
  }

  Future<void> saveChallenge(Challenge challenge) async {
    final box = await _openBox();
    await box.put(challenge.id, challenge);
  }

  Future<void> deleteChallenge(String id) async {
    final box = await _openBox();
    await box.delete(id);
  }

  Future<void> closeBox() async {
    if (Hive.isBoxOpen(challengesBoxName)) {
      await Hive.box<Challenge>(challengesBoxName).close();
    }
  }
}
